version: "3.8"
services:
  deno:
    build:
      context: .
      dockerfile: Dockerfile.deno
    ports:
      - 8081:8080
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 500M
        reservations:
          cpus: '0.1'
          memory: 500M

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - 8082:8080
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 500M
        reservations:
          cpus: '0.1'
          memory: 500M

  golang:
    build:
      context: .
      dockerfile: Dockerfile.golang
    ports:
      - 8083:8080
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 500M
        reservations:
          cpus: '0.1'
          memory: 500M

